export const RAW_PAGES = [
  {
    "": "1.0",
    "PageTitle": "Emergency Locksmith Canada - 24/7 Fast Response Call Now",
    "PageSlug": "/emergency-locksmith",
    "PrimaryKeyword": "emergency locksmith",
    "SecondaryKeywords": "emergency locksmith near me, 24 hour locksmith, emergency lockout service, emergency locksmith service canada",
    "TargetArea": "Canada (National)",
    "PageType": "Emergency Landing",
    "SearchIntent": "Transactional",
    "VolMo": "450.0",
    "Kd": "26.0",
    "Cpc": "200.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "2.0",
    "PageTitle": "24 Hour Locksmith Canada - Round the Clock Lockout Help",
    "PageSlug": "/24-hour-locksmith",
    "PrimaryKeyword": "24 hour locksmith",
    "SecondaryKeywords": "24 hour locksmith near me, 24/7 locksmith, all night locksmith, round the clock locksmith",
    "TargetArea": "Canada (National)",
    "PageType": "Emergency Landing",
    "SearchIntent": "Transactional",
    "VolMo": "200.0",
    "Kd": "10.0",
    "Cpc": "160.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "3.0",
    "PageTitle": "Emergency Lockout Service Canada - Locked Out? Call Now",
    "PageSlug": "/emergency-lockout-service",
    "PrimaryKeyword": "lockout service",
    "SecondaryKeywords": "emergency lockout service, lockout service near me, 24 hour lockout service, car and home lockout",
    "TargetArea": "Canada (National)",
    "PageType": "Emergency Landing",
    "SearchIntent": "Transactional",
    "VolMo": "200.0",
    "Kd": "3.0",
    "Cpc": "150.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "4.0",
    "PageTitle": "Locksmith Near Me - Local Locksmith Services Across Canada",
    "PageSlug": "/locksmith-near-me",
    "PrimaryKeyword": "locksmith near me",
    "SecondaryKeywords": "local locksmith, locksmith services near me, nearest locksmith, mobile locksmith near me",
    "TargetArea": "Canada (National)",
    "PageType": "Near Me Page",
    "SearchIntent": "Transactional",
    "VolMo": "5800.0",
    "Kd": "26.0",
    "Cpc": "200.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "5.0",
    "PageTitle": "Car Locksmith Near Me - Auto Lockout Help Across Canada",
    "PageSlug": "/car-locksmith-near-me",
    "PrimaryKeyword": "car locksmith near me",
    "SecondaryKeywords": "automotive locksmith near me, auto locksmith near me, vehicle locksmith, car lockout near me",
    "TargetArea": "Canada (National)",
    "PageType": "Near Me Page",
    "SearchIntent": "Transactional",
    "VolMo": "500.0",
    "Kd": "10.0",
    "Cpc": "140.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "6.0",
    "PageTitle": "Mobile Locksmith Canada - We Come to You, Fast",
    "PageSlug": "/mobile-locksmith",
    "PrimaryKeyword": "mobile locksmith",
    "SecondaryKeywords": "mobile locksmith near me, mobile locksmith service, on-site locksmith, locksmith that comes to you",
    "TargetArea": "Canada (National)",
    "PageType": "Service Pillar",
    "SearchIntent": "Transactional",
    "VolMo": "350.0",
    "Kd": "6.0",
    "Cpc": "190.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "7.0",
    "PageTitle": "Car Locksmith Canada - Automotive Lockout Specialists",
    "PageSlug": "/car-locksmith",
    "PrimaryKeyword": "car locksmith",
    "SecondaryKeywords": "automotive locksmith, auto locksmith, vehicle lockout service, car key locksmith",
    "TargetArea": "Canada (National)",
    "PageType": "Service Pillar",
    "SearchIntent": "Transactional",
    "VolMo": "600.0",
    "Kd": "0.0",
    "Cpc": "200.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "8.0",
    "PageTitle": "Locksmith Services Canada - Full Range of Lock Solutions",
    "PageSlug": "/locksmith-services",
    "PrimaryKeyword": "locksmith services",
    "SecondaryKeywords": "locksmith service canada, residential locksmith, commercial locksmith, local locksmith services",
    "TargetArea": "Canada (National)",
    "PageType": "Service Pillar",
    "SearchIntent": "Commercial",
    "VolMo": "350.0",
    "Kd": "21.0",
    "Cpc": "200.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "9.0",
    "PageTitle": "Commercial Locksmith Near Me - Business Locksmith Services Canada",
    "PageSlug": "/commercial-locksmith-near-me",
    "PrimaryKeyword": "commercial locksmith near me",
    "SecondaryKeywords": "commercial locksmith, commercial locksmith services, business locksmith, office locksmith near me",
    "TargetArea": "Canada (National)",
    "PageType": "Near Me Page",
    "SearchIntent": "Commercial",
    "VolMo": "200.0",
    "Kd": "22.0",
    "Cpc": "700.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "10.0",
    "PageTitle": "Locked Keys in Car Canada - Fast Unlock Service 24/7",
    "PageSlug": "/locked-keys-in-car",
    "PrimaryKeyword": "locked keys in car",
    "SecondaryKeywords": "keys locked in car, locked my keys in my car, car keys locked inside, i locked my keys in my car",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "600.0",
    "Kd": "6.0",
    "Cpc": "160.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "11.0",
    "PageTitle": "Locked Out of Car Canada - Call for Immediate Help",
    "PageSlug": "/locked-out-of-car",
    "PrimaryKeyword": "locked out of car",
    "SecondaryKeywords": "locked out of my car, locked out of vehicle, car lockout service, locked my keys in my car",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "400.0",
    "Kd": "2.0",
    "Cpc": "250.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "12.0",
    "PageTitle": "Car Lockout Service Canada - Locked Out? We Unlock Fast",
    "PageSlug": "/car-lockout-service",
    "PrimaryKeyword": "car lockout service",
    "SecondaryKeywords": "car lockout service near me, vehicle lockout service, locked out of car service, auto lockout",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "150.0",
    "Kd": "0.0",
    "Cpc": "200.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "13.0",
    "PageTitle": "Vehicle Lockout Service Canada - Fast Roadside Car Unlock",
    "PageSlug": "/vehicle-lockout-service",
    "PrimaryKeyword": "vehicle lockout service",
    "SecondaryKeywords": "vehicle lockout, car lockout, auto lockout service, roadside vehicle lockout",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "350.0",
    "Kd": "0.0",
    "Cpc": "120.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "14.0",
    "PageTitle": "Locked Out of Vehicle Canada - Same-Day Automotive Unlock",
    "PageSlug": "/locked-out-of-vehicle",
    "PrimaryKeyword": "locked out of vehicle",
    "SecondaryKeywords": "locked out of car canada, vehicle lockout service, locked out of truck, locked out of suv",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "350.0",
    "Kd": "0.0",
    "Cpc": "120.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "15.0",
    "PageTitle": "Roadside Assistance Canada - Lockout Help When You Need It",
    "PageSlug": "/roadside-assistance-lockout",
    "PrimaryKeyword": "roadside assistance",
    "SecondaryKeywords": "emergency roadside assistance, roadside assistance near me, car roadside assistance, roadside lockout help",
    "TargetArea": "Canada (National)",
    "PageType": "Service Pillar",
    "SearchIntent": "Transactional",
    "VolMo": "1900.0",
    "Kd": "3.0",
    "Cpc": "150.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "16.0",
    "PageTitle": "Roadside Assistance Near Me - Fast Lockout Response",
    "PageSlug": "/roadside-assistance-near-me",
    "PrimaryKeyword": "roadside assistance near me",
    "SecondaryKeywords": "emergency roadside assistance near me, roadside help near me, nearest roadside assistance, car lockout roadside",
    "TargetArea": "Canada (National)",
    "PageType": "Near Me Page",
    "SearchIntent": "Transactional",
    "VolMo": "450.0",
    "Kd": "4.0",
    "Cpc": "150.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "17.0",
    "PageTitle": "Emergency Roadside Assistance Canada - Locked Out on the Road?",
    "PageSlug": "/emergency-roadside-assistance",
    "PrimaryKeyword": "emergency roadside assistance",
    "SecondaryKeywords": "emergency roadside assistance near me, 24 hour roadside assistance, urgent roadside help, stranded locked out",
    "TargetArea": "Canada (National)",
    "PageType": "Emergency Landing",
    "SearchIntent": "Transactional",
    "VolMo": "250.0",
    "Kd": "4.0",
    "Cpc": "150.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "18.0",
    "PageTitle": "Key Cutting Near Me - Professional Key Cutting Across Canada",
    "PageSlug": "/key-cutting-near-me",
    "PrimaryKeyword": "key cutting near me",
    "SecondaryKeywords": "key cutting, key duplicate near me, duplicate key near me, key cutting service",
    "TargetArea": "Canada (National)",
    "PageType": "Near Me Page",
    "SearchIntent": "Transactional",
    "VolMo": "2800.0",
    "Kd": "0.0",
    "Cpc": "110.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "19.0",
    "PageTitle": "Duplicate Key Near Me - Copy Your Keys Fast Across Canada",
    "PageSlug": "/duplicate-key-near-me",
    "PrimaryKeyword": "duplicate key near me",
    "SecondaryKeywords": "key duplicate near me, copy key near me, duplicate house key, key duplication service",
    "TargetArea": "Canada (National)",
    "PageType": "Near Me Page",
    "SearchIntent": "Transactional",
    "VolMo": "400.0",
    "Kd": "7.0",
    "Cpc": "130.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "20.0",
    "PageTitle": "Key Fob Replacement Canada - Car Remote Replacement Service",
    "PageSlug": "/key-fob-replacement",
    "PrimaryKeyword": "key fob replacement",
    "SecondaryKeywords": "key fob replacement near me, car key fob replacement, replacement key fob, key fob programming",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "600.0",
    "Kd": "0.0",
    "Cpc": "35.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "21.0",
    "PageTitle": "Transponder Key Programming Canada - Automotive Key Specialist",
    "PageSlug": "/transponder-key-programming",
    "PrimaryKeyword": "transponder key programming",
    "SecondaryKeywords": "transponder key, transponder key replacement, car chip key programming, auto key programming",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Commercial",
    "VolMo": "150.0",
    "Kd": "0.0",
    "Cpc": "0.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "22.0",
    "PageTitle": "Lock Change Service Canada - Change Your Locks Fast",
    "PageSlug": "/lock-change",
    "PrimaryKeyword": "lock change",
    "SecondaryKeywords": "change lock, door lock change, lock replacement, rekey lock service",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Transactional",
    "VolMo": "100.0",
    "Kd": "1.0",
    "Cpc": "180.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "23.0",
    "PageTitle": "Mobile Key Cutting Canada - We Come to You",
    "PageSlug": "/mobile-key-cutting",
    "PrimaryKeyword": "mobile key cutting",
    "SecondaryKeywords": "mobile key cutting near me, on-site key cutting, mobile locksmith key cutting, key cutting at home",
    "TargetArea": "Canada (National)",
    "PageType": "Service Page",
    "SearchIntent": "Commercial",
    "VolMo": "100.0",
    "Kd": "24.0",
    "Cpc": "140.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "24.0",
    "PageTitle": "Locksmith Mississauga - 24/7 Lockout Service Call Now",
    "PageSlug": "/locksmith-mississauga",
    "PrimaryKeyword": "locksmith mississauga",
    "SecondaryKeywords": "locksmith near me mississauga, car lockout mississauga, emergency locksmith mississauga, locked out mississauga",
    "TargetArea": "Mississauga, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "1100.0",
    "Kd": "26.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "25.0",
    "PageTitle": "Locksmith Etobicoke - Fast Lockout Help Near You",
    "PageSlug": "/locksmith-etobicoke",
    "PrimaryKeyword": "locksmith etobicoke",
    "SecondaryKeywords": "locksmith near me etobicoke, car lockout etobicoke, emergency locksmith etobicoke, keys locked in car etobicoke",
    "TargetArea": "Etobicoke, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "700.0",
    "Kd": "19.0",
    "Cpc": "500.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "26.0",
    "PageTitle": "Locksmith Toronto - 24/7 Lockout and Key Service",
    "PageSlug": "/locksmith-toronto",
    "PrimaryKeyword": "locksmith toronto",
    "SecondaryKeywords": "toronto locksmith, locksmith near me toronto, car lockout toronto, emergency locksmith toronto",
    "TargetArea": "Toronto, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "1200.0",
    "Kd": "38.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "27.0",
    "PageTitle": "Locksmith Brampton - Local Lockout and Key Experts",
    "PageSlug": "/locksmith-brampton",
    "PrimaryKeyword": "locksmith brampton",
    "SecondaryKeywords": "locksmith near me brampton, car lockout brampton, emergency locksmith brampton, key cutting brampton",
    "TargetArea": "Brampton, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "700.0",
    "Kd": "12.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "28.0",
    "PageTitle": "Locksmith Oakville - Residential and Auto Lockout Service",
    "PageSlug": "/locksmith-oakville",
    "PrimaryKeyword": "locksmith oakville",
    "SecondaryKeywords": "locksmith near me oakville, car lockout oakville, emergency locksmith oakville, locked out oakville",
    "TargetArea": "Oakville, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "450.0",
    "Kd": "24.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "29.0",
    "PageTitle": "Locksmith Burlington - Fast Local Locksmith On Call",
    "PageSlug": "/locksmith-burlington",
    "PrimaryKeyword": "locksmith burlington",
    "SecondaryKeywords": "locksmith near me burlington, car lockout burlington, emergency locksmith burlington, key cutting burlington",
    "TargetArea": "Burlington, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "400.0",
    "Kd": "15.0",
    "Cpc": "450.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "30.0",
    "PageTitle": "Locksmith Hamilton - 24/7 Lockout and Key Services",
    "PageSlug": "/locksmith-hamilton",
    "PrimaryKeyword": "locksmith hamilton",
    "SecondaryKeywords": "hamilton locksmith, locksmith near me hamilton, car lockout hamilton, emergency locksmith hamilton",
    "TargetArea": "Hamilton, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "700.0",
    "Kd": "37.0",
    "Cpc": "400.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "31.0",
    "PageTitle": "Locksmith Vaughan - Local Locksmith Available Now",
    "PageSlug": "/locksmith-vaughan",
    "PrimaryKeyword": "locksmith vaughan",
    "SecondaryKeywords": "locksmith near me vaughan, car lockout vaughan, emergency locksmith vaughan, locked out vaughan",
    "TargetArea": "Vaughan, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "400.0",
    "Kd": "14.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "32.0",
    "PageTitle": "Locksmith North York - Fast Lockout Response North York",
    "PageSlug": "/locksmith-north-york",
    "PrimaryKeyword": "locksmith north york",
    "SecondaryKeywords": "locksmith near me north york, car lockout north york, emergency locksmith north york, 24 hour locksmith north york",
    "TargetArea": "North York, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "350.0",
    "Kd": "1.0",
    "Cpc": "350.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "33.0",
    "PageTitle": "Locksmith Scarborough - Your Local Lockout Experts",
    "PageSlug": "/locksmith-scarborough",
    "PrimaryKeyword": "locksmith scarborough",
    "SecondaryKeywords": "locksmith near me scarborough, car lockout scarborough, emergency locksmith scarborough, key cutting scarborough",
    "TargetArea": "Scarborough, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "500.0",
    "Kd": "21.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "34.0",
    "PageTitle": "Locksmith Markham - Residential and Auto Locksmith",
    "PageSlug": "/locksmith-markham",
    "PrimaryKeyword": "locksmith markham",
    "SecondaryKeywords": "locksmith near me markham, car lockout markham, emergency locksmith markham, locked out markham",
    "TargetArea": "Markham, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "250.0",
    "Kd": "7.0",
    "Cpc": "300.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "35.0",
    "PageTitle": "Locksmith Richmond Hill - 24/7 Locksmith Available",
    "PageSlug": "/locksmith-richmond-hill",
    "PrimaryKeyword": "locksmith richmond hill",
    "SecondaryKeywords": "locksmith near me richmond hill, car lockout richmond hill, emergency locksmith richmond hill, key cutting richmond hill",
    "TargetArea": "Richmond Hill, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "250.0",
    "Kd": "9.0",
    "Cpc": "300.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "36.0",
    "PageTitle": "Locksmith Newmarket - Fast Lockout Help in Newmarket",
    "PageSlug": "/locksmith-newmarket",
    "PrimaryKeyword": "locksmith newmarket",
    "SecondaryKeywords": "locksmith near me newmarket, car lockout newmarket, emergency locksmith newmarket, locked out newmarket",
    "TargetArea": "Newmarket, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "250.0",
    "Kd": "13.0",
    "Cpc": "300.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "37.0",
    "PageTitle": "Locksmith Oshawa - Local Lockout and Key Service",
    "PageSlug": "/locksmith-oshawa",
    "PrimaryKeyword": "locksmith oshawa",
    "SecondaryKeywords": "locksmith near me oshawa, car lockout oshawa, emergency locksmith oshawa, key cutting oshawa",
    "TargetArea": "Oshawa, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "500.0",
    "Kd": "15.0",
    "Cpc": "180.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "38.0",
    "PageTitle": "Locksmith Whitby - Professional Locksmith in Whitby",
    "PageSlug": "/locksmith-whitby",
    "PrimaryKeyword": "locksmith whitby",
    "SecondaryKeywords": "locksmith near me whitby, car lockout whitby, emergency locksmith whitby, locked out whitby",
    "TargetArea": "Whitby, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "250.0",
    "Kd": "23.0",
    "Cpc": "250.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "39.0",
    "PageTitle": "Locksmith Kitchener - Lockout and Key Services in Kitchener",
    "PageSlug": "/locksmith-kitchener",
    "PrimaryKeyword": "locksmith kitchener",
    "SecondaryKeywords": "locksmith near me kitchener, car lockout kitchener, emergency locksmith kitchener, key cutting kitchener",
    "TargetArea": "Kitchener, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "350.0",
    "Kd": "22.0",
    "Cpc": "160.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "40.0",
    "PageTitle": "Locksmith Guelph - Fast Local Locksmith Service",
    "PageSlug": "/locksmith-guelph",
    "PrimaryKeyword": "locksmith guelph",
    "SecondaryKeywords": "locksmith near me guelph, car lockout guelph, emergency locksmith guelph, locked out guelph",
    "TargetArea": "Guelph, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "300.0",
    "Kd": "8.0",
    "Cpc": "160.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "41.0",
    "PageTitle": "Locksmith Windsor - Windsor Locksmith Available 24/7",
    "PageSlug": "/locksmith-windsor",
    "PrimaryKeyword": "locksmith windsor",
    "SecondaryKeywords": "locksmith near me windsor, car lockout windsor, emergency locksmith windsor, key cutting windsor",
    "TargetArea": "Windsor, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "400.0",
    "Kd": "24.0",
    "Cpc": "60.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "42.0",
    "PageTitle": "Locksmith London Ontario - Local Lockout Experts",
    "PageSlug": "/locksmith-london-ontario",
    "PrimaryKeyword": "locksmith london ontario",
    "SecondaryKeywords": "locksmith near me london ontario, car lockout london ontario, emergency locksmith london, locked out london ontario",
    "TargetArea": "London, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "400.0",
    "Kd": "28.0",
    "Cpc": "170.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "43.0",
    "PageTitle": "Locksmith Kanata - 24/7 Locksmith Service in Kanata",
    "PageSlug": "/locksmith-kanata",
    "PrimaryKeyword": "locksmith kanata",
    "SecondaryKeywords": "locksmith near me kanata, car lockout kanata, emergency locksmith kanata, locked out kanata",
    "TargetArea": "Kanata, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "300.0",
    "Kd": "7.0",
    "Cpc": "150.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "44.0",
    "PageTitle": "Locksmith Barrie - Residential and Auto Lockout in Barrie",
    "PageSlug": "/locksmith-barrie",
    "PrimaryKeyword": "locksmith barrie",
    "SecondaryKeywords": "locksmith near me barrie, car lockout barrie, emergency locksmith barrie, key cutting barrie",
    "TargetArea": "Barrie, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "17.0",
    "Cpc": "160.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "45.0",
    "PageTitle": "Locksmith Brantford - Local Lock and Key Specialist",
    "PageSlug": "/locksmith-brantford",
    "PrimaryKeyword": "locksmith brantford",
    "SecondaryKeywords": "locksmith near me brantford, car lockout brantford, emergency locksmith brantford, locked out brantford",
    "TargetArea": "Brantford, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "6.0",
    "Cpc": "160.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "46.0",
    "PageTitle": "Locksmith Cambridge - Fast Lockout Service in Cambridge",
    "PageSlug": "/locksmith-cambridge",
    "PrimaryKeyword": "locksmith cambridge",
    "SecondaryKeywords": "locksmith near me cambridge, car lockout cambridge, emergency locksmith cambridge, key cutting cambridge",
    "TargetArea": "Cambridge, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "7.0",
    "Cpc": "250.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "47.0",
    "PageTitle": "Locksmith St Catharines - Locksmith Service in St Catharines",
    "PageSlug": "/locksmith-st-catharines",
    "PrimaryKeyword": "st catharines locksmith",
    "SecondaryKeywords": "locksmith near me st catharines, car lockout st catharines, emergency locksmith st catharines, locked out st catharines",
    "TargetArea": "St Catharines, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "350.0",
    "Kd": "9.0",
    "Cpc": "0.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "48.0",
    "PageTitle": "Locksmith Pickering - Fast Lockout and Key Service Pickering",
    "PageSlug": "/locksmith-pickering",
    "PrimaryKeyword": "locksmith pickering",
    "SecondaryKeywords": "locksmith near me pickering, car lockout pickering, emergency locksmith pickering, locked out pickering",
    "TargetArea": "Pickering, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "7.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "49.0",
    "PageTitle": "Locksmith Waterloo - 24/7 Locksmith Service in Waterloo ON",
    "PageSlug": "/locksmith-waterloo",
    "PrimaryKeyword": "locksmith waterloo",
    "SecondaryKeywords": "locksmith near me waterloo, car lockout waterloo, emergency locksmith waterloo, key cutting waterloo",
    "TargetArea": "Waterloo, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "24.0",
    "Cpc": "200.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "50.0",
    "PageTitle": "Locksmith Kingston - Local Locksmith and Lockout Service Kingston",
    "PageSlug": "/locksmith-kingston",
    "PrimaryKeyword": "locksmith kingston",
    "SecondaryKeywords": "locksmith near me kingston, car lockout kingston, emergency locksmith kingston ontario, locked out kingston",
    "TargetArea": "Kingston, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "90.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "51.0",
    "PageTitle": "Locksmith Edmonton - 24/7 Lockout and Key Service Edmonton",
    "PageSlug": "/locksmith-edmonton",
    "PrimaryKeyword": "locksmith edmonton",
    "SecondaryKeywords": "locksmith near me edmonton, car lockout edmonton, emergency locksmith edmonton, keys locked in car edmonton",
    "TargetArea": "Edmonton, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "700.0",
    "Kd": "30.0",
    "Cpc": "300.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "52.0",
    "PageTitle": "Locksmith Airdrie - Fast Locksmith Service in Airdrie AB",
    "PageSlug": "/locksmith-airdrie",
    "PrimaryKeyword": "locksmith airdrie",
    "SecondaryKeywords": "locksmith near me airdrie, car lockout airdrie, emergency locksmith airdrie, locked out airdrie",
    "TargetArea": "Airdrie, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "7.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "53.0",
    "PageTitle": "Roadside Assistance Edmonton - Lockout Help in Edmonton",
    "PageSlug": "/roadside-assistance-edmonton",
    "PrimaryKeyword": "roadside assistance edmonton",
    "SecondaryKeywords": "emergency roadside assistance edmonton, car lockout edmonton, locked out car edmonton, edmonton locksmith roadside",
    "TargetArea": "Edmonton, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "150.0",
    "Kd": "2.0",
    "Cpc": "250.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "54.0",
    "PageTitle": "Locksmith Sherwood Park - Local Locksmith in Sherwood Park AB",
    "PageSlug": "/locksmith-sherwood-park",
    "PrimaryKeyword": "locksmith sherwood park",
    "SecondaryKeywords": "locksmith near me sherwood park, car lockout sherwood park, emergency locksmith sherwood park, locked out sherwood park",
    "TargetArea": "Sherwood Park, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "4.0",
    "Cpc": "250.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "55.0",
    "PageTitle": "Locksmith Lethbridge - 24/7 Locksmith Service in Lethbridge",
    "PageSlug": "/locksmith-lethbridge",
    "PrimaryKeyword": "locksmith lethbridge",
    "SecondaryKeywords": "locksmith near me lethbridge, car lockout lethbridge, emergency locksmith lethbridge, locked out lethbridge",
    "TargetArea": "Lethbridge, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "20.0",
    "Cpc": "80.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "56.0",
    "PageTitle": "Locksmith Chestermere - Lockout and Key Service Chestermere AB",
    "PageSlug": "/locksmith-chestermere",
    "PrimaryKeyword": "locksmith chestermere",
    "SecondaryKeywords": "locksmith near me chestermere, car lockout chestermere, emergency locksmith chestermere, locked out chestermere",
    "TargetArea": "Chestermere, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "0.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "57.0",
    "PageTitle": "Locksmith Vancouver - 24/7 Lockout Service in Vancouver",
    "PageSlug": "/locksmith-vancouver",
    "PrimaryKeyword": "locksmith vancouver",
    "SecondaryKeywords": "vancouver locksmith, locksmith near me vancouver, car lockout vancouver, emergency locksmith vancouver",
    "TargetArea": "Vancouver, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "2200.0",
    "Kd": "12.0",
    "Cpc": "350.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "58.0",
    "PageTitle": "Locksmith Burnaby - Local Locksmith and Lockout Help",
    "PageSlug": "/locksmith-burnaby",
    "PrimaryKeyword": "locksmith burnaby",
    "SecondaryKeywords": "locksmith near me burnaby, car lockout burnaby, emergency locksmith burnaby, key cutting burnaby",
    "TargetArea": "Burnaby, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "800.0",
    "Kd": "0.0",
    "Cpc": "350.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "59.0",
    "PageTitle": "Locksmith Richmond - Locksmith Services in Richmond BC",
    "PageSlug": "/locksmith-richmond",
    "PrimaryKeyword": "locksmith richmond",
    "SecondaryKeywords": "locksmith near me richmond bc, car lockout richmond, emergency locksmith richmond bc, key cutting richmond",
    "TargetArea": "Richmond, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "700.0",
    "Kd": "9.0",
    "Cpc": "300.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "60.0",
    "PageTitle": "Locksmith North Vancouver - Lockout and Key Services",
    "PageSlug": "/locksmith-north-vancouver",
    "PrimaryKeyword": "locksmith north vancouver",
    "SecondaryKeywords": "locksmith near me north vancouver, car lockout north vancouver, emergency locksmith north van, locked out north vancouver",
    "TargetArea": "North Vancouver, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "450.0",
    "Kd": "12.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "61.0",
    "PageTitle": "Locksmith Coquitlam - 24/7 Locksmith in Coquitlam BC",
    "PageSlug": "/locksmith-coquitlam",
    "PrimaryKeyword": "locksmith coquitlam",
    "SecondaryKeywords": "locksmith near me coquitlam, car lockout coquitlam, emergency locksmith coquitlam, locked out coquitlam",
    "TargetArea": "Coquitlam, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "500.0",
    "Kd": "0.0",
    "Cpc": "300.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "62.0",
    "PageTitle": "Locksmith Langley - Professional Locksmith in Langley BC",
    "PageSlug": "/locksmith-langley",
    "PrimaryKeyword": "locksmith langley",
    "SecondaryKeywords": "locksmith near me langley, car lockout langley, emergency locksmith langley bc, key cutting langley",
    "TargetArea": "Langley, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "400.0",
    "Kd": "4.0",
    "Cpc": "350.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "63.0",
    "PageTitle": "Locksmith Abbotsford - Local Locksmith in Abbotsford BC",
    "PageSlug": "/locksmith-abbotsford",
    "PrimaryKeyword": "locksmith abbotsford",
    "SecondaryKeywords": "locksmith near me abbotsford, car lockout abbotsford, emergency locksmith abbotsford, locked out abbotsford",
    "TargetArea": "Abbotsford, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "300.0",
    "Kd": "8.0",
    "Cpc": "160.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "64.0",
    "PageTitle": "Locksmith New Westminster - Lockout Help in New Westminster",
    "PageSlug": "/locksmith-new-westminster",
    "PrimaryKeyword": "locksmith new westminster",
    "SecondaryKeywords": "locksmith near me new westminster, car lockout new westminster, emergency locksmith new westminster, locked out new west",
    "TargetArea": "New Westminster, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "300.0",
    "Kd": "0.0",
    "Cpc": "350.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "65.0",
    "PageTitle": "Locksmith Victoria - 24/7 Locksmith Service in Victoria BC",
    "PageSlug": "/locksmith-victoria",
    "PrimaryKeyword": "locksmith victoria",
    "SecondaryKeywords": "locksmith near me victoria bc, car lockout victoria, emergency locksmith victoria bc, key cutting victoria",
    "TargetArea": "Victoria, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "300.0",
    "Kd": "28.0",
    "Cpc": "80.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "66.0",
    "PageTitle": "Roadside Assistance Vancouver - Lockout Help on BC Roads",
    "PageSlug": "/roadside-assistance-vancouver",
    "PrimaryKeyword": "roadside assistance vancouver",
    "SecondaryKeywords": "emergency roadside assistance vancouver, car lockout vancouver, locked out car vancouver bc, bc roadside lockout",
    "TargetArea": "Vancouver, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "150.0",
    "Kd": "0.0",
    "Cpc": "150.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "67.0",
    "PageTitle": "Locksmith Surrey - 24/7 Lockout and Key Service Surrey",
    "PageSlug": "/locksmith-surrey",
    "PrimaryKeyword": "locksmith surrey",
    "SecondaryKeywords": "locksmith near me surrey, car lockout surrey, emergency locksmith surrey bc, key cutting surrey",
    "TargetArea": "Surrey, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "1000.0",
    "Kd": "42.0",
    "Cpc": "190.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "68.0",
    "PageTitle": "Locksmith Maple Ridge - Local Locksmith in Maple Ridge BC",
    "PageSlug": "/locksmith-maple-ridge",
    "PrimaryKeyword": "locksmith maple ridge",
    "SecondaryKeywords": "locksmith near me maple ridge, car lockout maple ridge, emergency locksmith maple ridge bc, locked out maple ridge",
    "TargetArea": "Maple Ridge, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "10.0",
    "Cpc": "300.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "69.0",
    "PageTitle": "Locksmith Ottawa - 24/7 Lockout Service in Ottawa",
    "PageSlug": "/locksmith-ottawa",
    "PrimaryKeyword": "locksmith ottawa",
    "SecondaryKeywords": "ottawa locksmith, locksmith near me ottawa, car lockout ottawa, 24 hour locksmith ottawa",
    "TargetArea": "Ottawa, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "2200.0",
    "Kd": "29.0",
    "Cpc": "450.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "70.0",
    "PageTitle": "24 Hour Locksmith Ottawa - Ottawa Emergency Lockout Help",
    "PageSlug": "/24-hour-locksmith-ottawa",
    "PrimaryKeyword": "24 hour locksmith ottawa",
    "SecondaryKeywords": "emergency locksmith ottawa, 24/7 locksmith ottawa, overnight locksmith ottawa, locksmith ottawa after hours",
    "TargetArea": "Ottawa, ON",
    "PageType": "Emergency Landing",
    "SearchIntent": "Transactional",
    "VolMo": "150.0",
    "Kd": "19.0",
    "Cpc": "600.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "71.0",
    "PageTitle": "Locksmith Gatineau - Locksmith Service in Gatineau QC",
    "PageSlug": "/locksmith-gatineau",
    "PrimaryKeyword": "locksmith gatineau",
    "SecondaryKeywords": "locksmith near me gatineau, car lockout gatineau, emergency locksmith gatineau, locked out gatineau",
    "TargetArea": "Gatineau, QC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "300.0",
    "Kd": "0.0",
    "Cpc": "200.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "72.0",
    "PageTitle": "Roadside Assistance Ottawa - Lockout on Ottawa Roads?",
    "PageSlug": "/roadside-assistance-ottawa",
    "PrimaryKeyword": "roadside assistance ottawa",
    "SecondaryKeywords": "emergency roadside assistance ottawa, car lockout ottawa, locked out car ottawa, ottawa roadside lockout",
    "TargetArea": "Ottawa, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "150.0",
    "Kd": "0.0",
    "Cpc": "180.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "73.0",
    "PageTitle": "Locksmith Orleans - Fast Locksmith Service in Orleans ON",
    "PageSlug": "/locksmith-orleans",
    "PrimaryKeyword": "locksmith orleans",
    "SecondaryKeywords": "locksmith near me orleans, car lockout orleans, emergency locksmith orleans ottawa, locked out orleans",
    "TargetArea": "Orleans, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "200.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "74.0",
    "PageTitle": "Locksmith LaSalle - Lockout and Key Service in LaSalle ON",
    "PageSlug": "/locksmith-lasalle",
    "PrimaryKeyword": "locksmith lasalle",
    "SecondaryKeywords": "locksmith near me lasalle, car lockout lasalle, emergency locksmith lasalle ontario, locked out lasalle",
    "TargetArea": "LaSalle, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "190.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "75.0",
    "PageTitle": "Locksmith Regina - Local Locksmith in Regina SK",
    "PageSlug": "/locksmith-regina",
    "PrimaryKeyword": "locksmith regina",
    "SecondaryKeywords": "locksmith near me regina, car lockout regina, emergency locksmith regina, key cutting regina",
    "TargetArea": "Regina, SK",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "450.0",
    "Kd": "8.0",
    "Cpc": "300.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "76.0",
    "PageTitle": "Locksmith Saskatoon - 24/7 Lockout and Key Service",
    "PageSlug": "/locksmith-saskatoon",
    "PrimaryKeyword": "locksmith saskatoon",
    "SecondaryKeywords": "locksmith near me saskatoon, car lockout saskatoon, emergency locksmith saskatoon, locked out saskatoon",
    "TargetArea": "Saskatoon, SK",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "19.0",
    "Cpc": "110.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "77.0",
    "PageTitle": "Locksmith Winnipeg - 24/7 Locksmith Service Winnipeg",
    "PageSlug": "/locksmith-winnipeg",
    "PrimaryKeyword": "locksmith winnipeg",
    "SecondaryKeywords": "locksmith near me winnipeg, car lockout winnipeg, emergency locksmith winnipeg, key cutting winnipeg",
    "TargetArea": "Winnipeg, MB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "500.0",
    "Kd": "37.0",
    "Cpc": "400.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "78.0",
    "PageTitle": "Locksmith Halifax - Local Locksmith in Halifax NS",
    "PageSlug": "/locksmith-halifax",
    "PrimaryKeyword": "locksmith halifax",
    "SecondaryKeywords": "locksmith near me halifax, car lockout halifax, emergency locksmith halifax, key cutting halifax",
    "TargetArea": "Halifax, NS",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "400.0",
    "Kd": "4.0",
    "Cpc": "180.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "79.0",
    "PageTitle": "Locksmith Sudbury - Lockout and Key Service Sudbury ON",
    "PageSlug": "/locksmith-sudbury",
    "PrimaryKeyword": "locksmith sudbury",
    "SecondaryKeywords": "locksmith near me sudbury, car lockout sudbury, emergency locksmith sudbury, locked out sudbury",
    "TargetArea": "Sudbury, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "45.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "80.0",
    "PageTitle": "Roadside Assistance Calgary - Lockout Help on Calgary Roads",
    "PageSlug": "/roadside-assistance-calgary",
    "PrimaryKeyword": "roadside assistance calgary",
    "SecondaryKeywords": "emergency roadside assistance calgary, car lockout calgary, locked out car calgary, calgary locksmith roadside",
    "TargetArea": "Calgary, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "200.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "81.0",
    "PageTitle": "Roadside Assistance Toronto - Locked Out in Toronto?",
    "PageSlug": "/roadside-assistance-toronto",
    "PrimaryKeyword": "roadside assistance toronto",
    "SecondaryKeywords": "emergency roadside assistance toronto, car lockout toronto, locked out car toronto, toronto roadside lockout",
    "TargetArea": "Toronto, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "3.0",
    "Cpc": "180.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "82.0",
    "PageTitle": "Locksmith Dartmouth - Fast Locksmith Service in Dartmouth NS",
    "PageSlug": "/locksmith-dartmouth",
    "PrimaryKeyword": "locksmith dartmouth",
    "SecondaryKeywords": "locksmith near me dartmouth, car lockout dartmouth, emergency locksmith dartmouth nova scotia, locked out dartmouth",
    "TargetArea": "Dartmouth, NS",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "2.0",
    "Cpc": "190.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "83.0",
    "PageTitle": "Key Cutting Vancouver - Professional Key Duplication Service",
    "PageSlug": "/key-cutting-vancouver",
    "PrimaryKeyword": "key cutting vancouver",
    "SecondaryKeywords": "duplicate key vancouver, key copy vancouver, mobile key cutting vancouver, car key cutting vancouver",
    "TargetArea": "Vancouver, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "250.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "84.0",
    "PageTitle": "Key Cutting Calgary - Fast Key Duplication in Calgary",
    "PageSlug": "/key-cutting-calgary",
    "PrimaryKeyword": "key cutting calgary",
    "SecondaryKeywords": "duplicate key calgary, key copy calgary, car key cutting calgary, house key cutting calgary",
    "TargetArea": "Calgary, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "200.0",
    "Kd": "0.0",
    "Cpc": "130.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "85.0",
    "PageTitle": "Key Cutting Toronto - Duplicate Keys Fast in Toronto",
    "PageSlug": "/key-cutting-toronto",
    "PrimaryKeyword": "key cutting toronto",
    "SecondaryKeywords": "key cutting toronto near me, duplicate key toronto, car key cutting toronto, key copy toronto",
    "TargetArea": "Toronto, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "150.0",
    "Kd": "1.0",
    "Cpc": "80.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "86.0",
    "PageTitle": "Key Cutting Surrey - Key Duplication Service in Surrey BC",
    "PageSlug": "/key-cutting-surrey",
    "PrimaryKeyword": "key cutting surrey",
    "SecondaryKeywords": "duplicate key surrey, key copy surrey bc, car key cutting surrey, house key surrey",
    "TargetArea": "Surrey, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "150.0",
    "Kd": "9.0",
    "Cpc": "250.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "87.0",
    "PageTitle": "Key Cutting Hamilton - Key Copy and Duplication Hamilton",
    "PageSlug": "/key-cutting-hamilton",
    "PrimaryKeyword": "key cutting hamilton",
    "SecondaryKeywords": "duplicate key hamilton, key copy hamilton on, car key cutting hamilton, house key hamilton",
    "TargetArea": "Hamilton, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "150.0",
    "Kd": "0.0",
    "Cpc": "190.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "88.0",
    "PageTitle": "Key Cutting Edmonton - Professional Key Duplication Edmonton",
    "PageSlug": "/key-cutting-edmonton",
    "PrimaryKeyword": "key cutting edmonton",
    "SecondaryKeywords": "duplicate key edmonton, key copy edmonton, car key cutting edmonton, house key edmonton",
    "TargetArea": "Edmonton, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "100.0",
    "Kd": "0.0",
    "Cpc": "150.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "89.0",
    "PageTitle": "Key Cutting Regina - Key Duplication and Cutting Regina SK",
    "PageSlug": "/key-cutting-regina",
    "PrimaryKeyword": "key cutting regina",
    "SecondaryKeywords": "duplicate key regina, key copy regina sk, car key cutting regina, house key regina",
    "TargetArea": "Regina, SK",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "100.0",
    "Kd": "16.0",
    "Cpc": "0.0",
    "Priority": "Medium",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "90.0",
    "PageTitle": "Locked Keys in Car Toronto - Call Us for Fast Help",
    "PageSlug": "/locked-keys-in-car-toronto",
    "PrimaryKeyword": "locked keys in car toronto",
    "SecondaryKeywords": "car lockout toronto, locked out of car toronto, keys in car toronto, auto lockout toronto",
    "TargetArea": "Toronto, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "40.0",
    "Kd": "0.0",
    "Cpc": "450.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "91.0",
    "PageTitle": "Locked Keys in Car Edmonton - Immediate Unlock Edmonton",
    "PageSlug": "/locked-keys-in-car-edmonton",
    "PrimaryKeyword": "locked keys in car edmonton",
    "SecondaryKeywords": "car lockout edmonton, locked out of car edmonton, keys in car edmonton, auto lockout edmonton",
    "TargetArea": "Edmonton, AB",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "50.0",
    "Kd": "23.0",
    "Cpc": "600.0",
    "Priority": "Top Priority",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "92.0",
    "PageTitle": "Locked Keys in Car Vancouver - Vancouver Car Unlock Now",
    "PageSlug": "/locked-keys-in-car-vancouver",
    "PrimaryKeyword": "locked keys in car vancouver",
    "SecondaryKeywords": "car lockout vancouver, locked out of car vancouver, keys locked in car vancouver, auto lockout vancouver",
    "TargetArea": "Vancouver, BC",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "30.0",
    "Kd": "0.0",
    "Cpc": "400.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  },
  {
    "": "93.0",
    "PageTitle": "Car Lockout Ottawa - Fast Vehicle Unlock in Ottawa",
    "PageSlug": "/car-lockout-ottawa",
    "PrimaryKeyword": "car lockout ottawa",
    "SecondaryKeywords": "locked keys in car ottawa, locked out of car ottawa, auto lockout ottawa, emergency car unlock ottawa",
    "TargetArea": "Ottawa, ON",
    "PageType": "City Service Page",
    "SearchIntent": "Local Transactional",
    "VolMo": "60.0",
    "Kd": "0.0",
    "Cpc": "0.0",
    "Priority": "High",
    "CtaStrategy": "Call 1-888-320-3769"
  }
] as const;
